---
namespace: crusty_rs
name: infra2csv
version: 1.0.0
readme: README.md

authors:
  - yasir hamadi alsahli <crusty.rusty.engine@gmail.com>

description: >-
  Infrastructure data collection and auditing collection for Ansible.
  Collects hardware, network, storage, security, and user information
  from target systems and exports to CSV/JSON formats. Enhanced version 6
  with improved compatibility for Rocky Linux, Alma Linux, and minimal environments.

license:
  - GPL-3.0-or-later

license_file: ''

tags:
  - infrastructure
  - audit
  - csv
  - monitoring
  - hardware
  - network
  - storage
  - security
  - users
  - reporting
  - data_collection
  - system_info
  - compliance
  - inventory

dependencies: {}

repository: https://github.com/crusty-rs/ansible-collection-infra2csv
documentation: https://github.com/crusty-rs/ansible-collection-infra2csv
homepage: https://github.com/crusty-rs/ansible-collection-infra2csv
issues: https://github.com/crusty-rs/ansible-collection-infra2csv/issues

build_ignore:
  - '*.pyc'
  - '*.retry'
  - '.git'
  - '.gitignore'
  - '.DS_Store'
  - 'tests/'
  - 'test_*'
  - '*.tar.gz'
  - 'tmp/'
  - '.ansible'
  - '__pycache__'
  - '*.tmp'
  - '.vscode'
  - '.idea'
