---
namespace: crusty_rs
name: infra2csv
version: 1.0.1

readme: README.md
authors:
  - Yasir Hamadi Alsahli <crusty.rusty.engine@gmail.com>

description: >
  Collects system info from all your hosts into structured CSVs on the control node.
  No Jinja loops, no remote writes. Just clean, centralized facts across 7 categories:
  hardware, network, storage, users, security, filesystem health, and schedulers.
  Built for audits, reporting, asset tracking, and migrations. Simple, expandable, and
  made for real-world Linux ops.

license:
  - MIT

tags:
  - infrastructure
  - monitoring
  - inventory
  - csv
  - reporting
  - auditing
  - dashboards
  - observability
  - powerbi
  - grafana
  - fact_collection
  - data_export
  - hardware
  - storage
  - network
  - security
  - linux
  - discovery
  - cloud_inventory
  - ansible_collection

dependencies: {}

repository: https://github.com/Crusty-rs/ansible-collection-infra2csv
documentation: https://github.com/Crusty-rs/ansible-collection-infra2csv/wiki
homepage: https://github.com/Crusty-rs/ansible-collection-infra2csv
issues: https://github.com/Crusty-rs/ansible-collection-infra2csv/issues

build_ignore:
  - .gitignore
  - .git
  - .github
  - .vscode
  - '*.pyc'
  - __pycache__
  - tests/output
  - docs/build
  - tester.sh
  - test_*.yml

