# Security Collection Role
- name: Ensure output directory exists for security data
  ansible.builtin.file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}"
    state: directory
    mode: '0755'

- name: Collect security baseline data (no headers)
  # This task calls your Python security_baseline.py module
  crusty_rs.infra2csv.security_baseline:
    output_path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/security_{{ inventory_hostname }}.csv"
    include_headers: false # Headers will be added during the merge on controller
  register: security_result

- name: Fetch security data to controller
  ansible.builtin.fetch:
    src: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/security_{{ inventory_hostname }}.csv"
    dest: "{{ controller_output_path | default('/tmp/infra2csv') }}/raw/"
    flat: yes
  # Only fetch if the module reported collecting entries (i.e., not empty data)
  when: security_result.entries is defined and security_result.entries > 0

- name: Cleanup security file on target
  ansible.builtin.file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/security_{{ inventory_hostname }}.csv"
    state: absent
  when: cleanup_target | default(true)
