---
# Security Baseline Collection Role
- name: Ensure output directory exists
  file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}"
    state: directory
    mode: '0755'

- name: Collect security baseline (no headers)
  crusty_rs.infra2csv.security_baseline:
    output_path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/security_{{ inventory_hostname }}.csv"
    include_headers: false
  register: security_result

- name: Fetch security data to controller
  fetch:
    src: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/security_{{ inventory_hostname }}.csv"
    dest: "{{ controller_output_path | default('/tmp/infra2csv') }}/raw/"
    flat: yes
  when: security_result.entries > 0

- name: Cleanup security file on target
  file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/security_{{ inventory_hostname }}.csv"
    state: absent
  when: cleanup_target | default(true)
