# Users Collection Role
- name: Ensure output directory exists for users data
  ansible.builtin.file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}"
    state: directory
    mode: '0755'

- name: Collect users data (no headers)
  # This task calls your Python users_csv.py module
  crusty_rs.infra2csv.users_csv:
    output_path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/users_{{ inventory_hostname }}.csv"
    include_headers: false # Headers will be added during the merge on controller
    # Ensure any user-specific parameters are passed here, e.g.:
    # include_system_users: true
  register: users_result

- name: Fetch users data to controller
  ansible.builtin.fetch:
    src: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/users_{{ inventory_hostname }}.csv"
    dest: "{{ controller_output_path | default('/tmp/infra2csv') }}/raw/"
    flat: yes
  # Only fetch if the module reported collecting entries (i.e., not empty data)
  when: users_result.entries is defined and users_result.entries > 0

- name: Cleanup users file on target
  ansible.builtin.file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/users_{{ inventory_hostname }}.csv"
    state: absent
  when: cleanup_target | default(true)
  # Similar cleanup considerations as with security_result
  # when: users_result.rc == 0 and users_result.entries is defined and users_result.entries > 0
