---
# Filesystem Health Collection Role
- name: Ensure output directory exists
  file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}"
    state: directory
    mode: '0755'

- name: Collect filesystem health (no headers)
  crusty_rs.infra2csv.filesystem_health:
    output_path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/filesystem_{{ inventory_hostname }}.csv"
    include_headers: false
  register: filesystem_result

- name: Fetch filesystem data to controller
  fetch:
    src: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/filesystem_{{ inventory_hostname }}.csv"
    dest: "{{ controller_output_path | default('/tmp/infra2csv') }}/raw/"
    flat: yes
  when: filesystem_result.entries > 0

- name: Cleanup filesystem file on target
  file:
    path: "{{ infra_output_path | default(ansible_env.HOME + '/infra2csv') }}/filesystem_{{ inventory_hostname }}.csv"
    state: absent
  when: cleanup_target | default(true)
